#!/usr/bin/env python3
"""
MCP Server Configuration Template

Generates the .mcp.json configuration file and registration snippets
for integrating generated MCP tools with Claude Code.

Used by: mcp_tool_creator.py (Phase 5 compound orchestrator)
Created: February 6, 2026
"""

import json
from typing import Dict, List, Any


# Claude Code MCP server config template (stdio transport)
def generate_mcp_config(
    tool_name: str,
    server_path: str,
    description: str = "",
    env_vars: Dict[str, str] = None,
) -> Dict[str, Any]:
    """Generate .mcp.json config entry for a tool server."""
    config = {
        "mcpServers": {
            tool_name: {
                "command": "python3",
                "args": [server_path, "--stdio"],
            }
        }
    }

    if env_vars:
        config["mcpServers"][tool_name]["env"] = env_vars

    return config


def generate_registration_snippet(
    tool_name: str,
    server_path: str,
    tools_count: int,
    description: str = "",
) -> str:
    """Generate a human-readable registration snippet."""
    return f"""# MCP Tool Registration: {tool_name}
# {description}
# Tools: {tools_count}
#
# To register with Claude Code, add to ~/.claude/.mcp.json:
#
# {{
#   "mcpServers": {{
#     "{tool_name}": {{
#       "command": "python3",
#       "args": ["{server_path}", "--stdio"]
#     }}
#   }}
# }}
#
# Or register via CLI:
#   claude mcp add {tool_name} python3 {server_path} --stdio
"""


# Test stub template
TEST_TEMPLATE = '''#!/usr/bin/env python3
"""
Test stub for MCP Tool: {tool_name}

Tests all tool handlers with example inputs.
Generated by: NLKE MCP Tool Creator (Phase 5)
"""

import json
import subprocess
import sys


def test_list_tools():
    """Test that --list-tools works."""
    result = subprocess.run(
        ["python3", "{server_path}", "--list-tools"],
        capture_output=True, text=True, timeout=10,
    )
    assert result.returncode == 0, f"list-tools failed: {{result.stderr}}"
    print("  list-tools: OK")


def test_self_test():
    """Test that --test works."""
    result = subprocess.run(
        ["python3", "{server_path}", "--test"],
        capture_output=True, text=True, timeout=30,
    )
    assert result.returncode == 0, f"self-test failed: {{result.stderr}}"
    print("  self-test: OK")


def test_stdio_protocol():
    """Test MCP protocol via stdio."""
    proc = subprocess.Popen(
        ["python3", "{server_path}", "--stdio"],
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        text=True,
    )

    # Send initialize
    init_msg = json.dumps({{
        "jsonrpc": "2.0", "id": 1, "method": "initialize",
        "params": {{"protocolVersion": "2024-11-05", "capabilities": {{}}}}
    }})
    proc.stdin.write(init_msg + "\\n")
    proc.stdin.flush()

    response = proc.stdout.readline()
    data = json.loads(response)
    assert data.get("id") == 1, f"Bad init response: {{data}}"
    print("  initialize: OK")

    # Send tools/list
    list_msg = json.dumps({{"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {{}}}})
    proc.stdin.write(list_msg + "\\n")
    proc.stdin.flush()

    response = proc.stdout.readline()
    data = json.loads(response)
    tools = data.get("result", {{}}).get("tools", [])
    assert len(tools) == {tools_count}, f"Expected {tools_count} tools, got {{len(tools)}}"
    print(f"  tools/list: OK ({{len(tools)}} tools)")

    proc.terminate()


if __name__ == "__main__":
    print("Testing MCP Tool: {tool_name}")
    print()
    try:
        test_list_tools()
        test_self_test()
        test_stdio_protocol()
        print()
        print("All tests passed!")
    except Exception as e:
        print(f"\\nTEST FAILED: {{e}}")
        sys.exit(1)
'''
